import Sidebar from '@/app/screens/Sidebar'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import styled, { ThemeProvider } from 'styled-components'
import AppContainer from '@/app/screens/AppContainer'
import Header from '@/app/screens/Header'
import { DirContextProvider } from '@/app/context/DirContext'
import { ContextMenuProvider } from '@/app/context/ContextMenu'
import NavigationContextProvider from '@/app/context/NavigationContext'
import { colors } from '@/app/theme/colors'
import { GlobalStyles } from '@/styles/GlobalStyles'

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeProvider theme={colors}>
        <GlobalStyles />
        <DirContextProvider>
          <NavigationContextProvider>
            <Header />
            <AppContainer>
              <Sidebar />
              <ContextMenuProvider>
                <MainContainer>
                  <Component {...pageProps} />
                </MainContainer>
              </ContextMenuProvider>
            </AppContainer>
          </NavigationContextProvider>
        </DirContextProvider>
      </ThemeProvider>
    </>
  )
}

const MainContainer = styled.div`
  border: 0;
  height: 100vh;
  overflow-y: scroll;
  color: white;
  padding: 15px 0;
  width: 100%;
`

export default App
